Scratch

A notebook for exploring Python, Jupyter, etc.

In [1]:
D = 100
d = 50

In [2]:
D

100

In [3]:
d

50

In [4]:
whos

Variable   Type    Data/Info
----------------------------
D          int     100
d          int     50


In [5]:
import numpy as np

In [6]:
Lx = 8
dx = 0.5
x = np.arange(start=0, stop=Lx, step=dx)
nx = len(x)

In [7]:
nx

16

In [8]:
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5])

In [9]:
x1 = np. linspace(start=0, stop=Lx, num=7, endpoint=True)

In [10]:
x1

array([0.        , 1.33333333, 2.66666667, 4.        , 5.33333333,
       6.66666667, 8.        ])

In [11]:
C = np.zeros_like(x)
C_left = 500
C_right = 0
C[x <= Lx//2] = C_left
C[x > Lx//2] = C_right

In [12]:
C

array([500., 500., 500., 500., 500., 500., 500., 500., 500.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.])

In [13]:
C[-1]

np.float64(0.0)

In [14]:
x[-1]

np.float64(7.5)

In [15]:
x[-2]

np.float64(7.0)

In [18]:
nx = len(x)
nx

16

In [19]:
x[nx-1]

np.float64(7.5)

In [20]:
x[15]

np.float64(7.5)